version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    depends_on:
      - addition-service
      - subtraction-service
      - multiplication-service
      - division-service
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  addition-service:
    build: ./addition
    hostname: addition-service
    ports:
      - 5051:5051
    networks:
      sample:
        aliases:
          - addition

  subtraction-service:
    build: ./subtraction
    hostname: subtraction-service
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - subtraction

  multiplication-service:
    build: ./multiplication
    hostname: multiplication-service
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - multiplication
  
  division-service:
    build: ./division
    hostname: division-service
    ports:
      - 5054:5054
    networks:
      sample:
        aliases:
          - division
networks:
  sample:
